
export const tableDataInvestedProducts = [
    {
        invoice: '001',
        name: 'T-Shirt',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '002',
        name: 'T-Shirt',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
        
    },
    {
        invoice: '003',
        name: 'Leggings',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '004',
        name: 'Leggings',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '005',
        name: 'Leggings',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'pencil',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'pencil',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'T-Shirt',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'T-Shirt',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'pencil',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'T-Shirt',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'T-Shirt',
        Quantity_Sold  : '18',
        Current_Stock  : '20',  
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20', 
    },
    {
        invoice: '006',
        name: 'T-Shirt',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'pencil',
        Quantity_Sold  : '18',
        Current_Stock  : '20', 
    },
    {
        invoice: '006',
        name: 'T-Shirt',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'T-Shirt',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'T-Shirt',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'pencil',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'T-Shirt',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'T-Shirt',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'pencil',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'pencil',
        Quantity_Sold  : '18',
        Current_Stock  : '20', 
    },
    {
        invoice: '006',
        name: 'T-Shirt',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'T-Shirt',
        Quantity_Sold  : '18',
        Current_Stock  : '20', 
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'Bag',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'T-Shirt',
        Quantity_Sold  : '18',
        Current_Stock  : '20', 
    },
    {
        invoice: '006',
        name: 'pencil',
        quantity: '29',
        purchse_value: '$500.00',
        total_value: '$4000.00',
        sold_value: '$7000.00'
        
    },
    {
        invoice: '006',
        name: 'T-Shirt',
        Quantity_Sold  : '18',
        Current_Stock  : '20',
    },
    {
        invoice: '006',
        name: 'T-Shirt',
        Quantity_Sold  : '18',
        Current_Stock  : '20', 
    },
    
];